fix for issue #88
btschwertfeger/python-kraken-sdk pull request #89
Opened 2023-05-16 02:11 UTC by andyDoucette

A fix for issue #88 .

Here i use the /private/BalanceEx endpoint to get the balance and corresponding amount held by a open order for each nonzero currency balance.  That allows me to very easily calculate get_balances in a way that accepts both "USD" and "ZUSD"

For my use case, I would probably directly use get_balances_and_excluded().  I assume that is what "BalanceEx" means.

If you're looking for info on BalanceEx, the only mention I've found of it from Kraken is in their [suggested API wrapper](https://support.kraken.com/hc/en-us/articles/360025180232-REST-API-command-line-client-Python-).  Their kind support people also suggested it to me.

2023-05-16 15:04 UTC, btschwertfeger requested changes

2023-05-16 15:04 UTC, btschwertfeger commented on kraken/spot/user/__init__.py
> +                available_balance=balance-Decimal(data['hold_trade'])
```suggestion
                available_balance=balance-Decimal(data["hold_trade"])
```

2023-05-16 15:04 UTC, btschwertfeger commented on kraken/spot/user/__init__.py
> +                balance = Decimal(data['balance'])
```suggestion
                balance = Decimal(data["balance"])
```

2023-05-16 15:04 UTC, btschwertfeger commented on kraken/spot/user/__init__.py
> +        available_balance: Decimal(0)
```suggestion
        available_balance: Decimal = Decimal(0)
```

2023-05-16 15:04 UTC, btschwertfeger commented on kraken/spot/user/__init__.py
> +        Returns the currenzies with a nonzero balance and the corresponding amount held by an open trade.
```suggestion
        Returns the currencies with a non-zero balance and the corresponding amount held by open orders.
```

2023-05-16 15:08 UTC, btschwertfeger requested changes

2023-05-16 15:08 UTC, btschwertfeger commented on kraken/spot/user/__init__.py
>      def get_balances(self: "User", currency: str) -> dict:
What about:

```suggestion
    def get_balance(self: "User", currency: str) -> dict:
```

2023-05-16 15:08 UTC, btschwertfeger commented on kraken/spot/user/__init__.py
> +    def get_balances_and_excluded(self: "User") -> dict:
The naming might be better, even its a breaking change.

```suggestion
    def get_balances(self: "User") -> dict:
```

2023-05-16 15:09 UTC, btschwertfeger commented
Hello @andyDoucette, thank you for your contribution!

I'm interested in merging your changes after you addressed the following issues: 
* Please add a unit test for the new method/endpoint. 
* Make sure that the CI/CD workflow run through and all jobs are green.
* Also see the suggestions I added above.

Have a nice day!

2023-05-18 07:22 UTC, andyDoucette commented
Thanks for your feedback.  I wasn't expecting to have to do more work to share the work I have already done with the rest of the world.  I'll try to get to this sometime, but to be honest I have a lot of other things vying for my time, so I am not sure when I would get to this.  If you are ok polishing this up, feel free.  If I get a break sometime in the next few months, maybe I will, but I would put it at a 20% chance or less.

I just feel good that at least the work I did already to solve the problem for myself is "out there" in case it makes anyone else's work a little easier.

2023-05-18 07:29 UTC, andyDoucette commented
I agree that the new naming is better, if you don't mind breaking changes or don't have many users yet.

2023-05-18 10:50 UTC, btschwertfeger commented
> Thanks for your feedback. I wasn't expecting to have to do more work to share the work I have already done with the rest of the world. I'll try to get to this sometime, but to be honest I have a lot of other things vying for my time, so I am not sure when I would get to this. If you are ok polishing this up, feel free. If I get a break sometime in the next few months, maybe I will, but I would put it at a 20% chance or less.
> 
> I just feel good that at least the work I did already to solve the problem for myself is "out there" in case it makes anyone else's work a little easier.

So I will do the last steps if that's ok for you.

2023-05-18 11:02 UTC, andyDoucette commented
That would be amazing.  Thank you so much for making this library, btw!

On Thu, May 18, 2023, 5:50 PM Benjamin T. Schwertfeger <
***@***.***> wrote:

> Thanks for your feedback. I wasn't expecting to have to do more work to
> share the work I have already done with the rest of the world. I'll try to
> get to this sometime, but to be honest I have a lot of other things vying
> for my time, so I am not sure when I would get to this. If you are ok
> polishing this up, feel free. If I get a break sometime in the next few
> months, maybe I will, but I would put it at a 20% chance or less.
>
> I just feel good that at least the work I did already to solve the problem
> for myself is "out there" in case it makes anyone else's work a little
> easier.
>
> So I will do the last steps if that's ok for you.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/btschwertfeger/python-kraken-sdk/pull/89#issuecomment-1552876330>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AEVLQ5WPSYK3SUIXJYMZHR3XGX5GXANCNFSM6AAAAAAYC6673M>
> .
> You are receiving this because you were mentioned.Message ID:
> ***@***.***>
>

2023-05-20 06:30 UTC, btschwertfeger commented
This enhancement will be addressed in the separate PR #98.

2023-05-20 06:30 UTC, closed without merging